### ISSUE TITLE
Keybind bug

### ISSUE THREAD

**Issue by Yoshi-RBLX** [mayo78/FNF-PsychEngine-BambiAddon#4]
### Describe your bug here.

I set my keybinds once and they stay the same until I close out the app and start it again, then it reverts back to default. Can you hopefully fix this next update?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by mayo78** [comment]
for some reason the game needs to boot up twice in order for the custom save to fully work, no idea why! ill keep this issue open till its fixed

**Comment by mayo78** [comment]
yay i fix it :)
