### ISSUE TITLE
Question about the Wavy BG Shader

### ISSUE THREAD

**Issue by Yoshi-RBLX** [mayo78/FNF-PsychEngine-BambiAddon#7]
### What is your question?

I know there's a shader in the build "Glitch Shader" which makes the Wavy BG, but I don't know how to implement it into a stage, what do I use to add the shader onto a lua sprite?

**Comment by mayo78** [comment]
ill add examples next update for people to follow, ill close this when i get done with that

**Comment by mayo78** [comment]
closed cause im making an example mod rn with all the features of this thing
